# mkdocs.yml
site_name: Design_Drafter
site_url: https://sites.uab.edu/periop-datascience/
repo_url: https://github.com/uabperiopai
nav:
  - Home: index.md
  - 'Design_Drafter':
    - Streamlit Interface: 'Design_Drafter/sample_handler.md'
    - User Interface: 'Design_Drafter_streamlit_app.md'
    - Example: 'Design_Drafter/utils/utils_example.md'
  - 'Design_Drafter/config':
    - Config: 'Design_Drafter/config/config.md'

  - llm_utils: '!include ./llm_utils/mkdocs.yml'

theme:
  name: readthedocs
plugins:
  - search
  - monorepo:
      submodules:
        - path: llm_utils
          repo_url: ''
  - mkdocstrings:
      handlers:
        python:
          paths: ['Design_Drafter', 'Design_Drafter/config', user_interface, llm_utils]  # search packages in these folders
watch:
  - .  # reload docs for any file changes
use_directory_urls: false