# mkdocs.yml
site_name: UMLBot
site_url: https://sites.uab.edu/periop-datascience/
repo_url: https://github.com/uabperiopai
nav:
  - Home: index.md
  - 'UMLBot':
    - Streamlit Interface: 'UMLBot/sample_handler.md'
    - User Interface: 'UMLBot_streamlit_app.md'
    - Example: 'UMLBot/utils/utils_example.md'
  - 'UMLBot/config':
    - Config: 'UMLBot/config/config.md'

  - llm_utils: '!include ./llm_utils/mkdocs.yml'

theme:
  name: readthedocs
plugins:
  - search
  - monorepo:
      submodules:
        - path: llm_utils
          repo_url: ''
  - mkdocstrings:
      handlers:
        python:
          paths: ['UMLBot', 'UMLBot/config', user_interface, llm_utils]  # search packages in these folders
watch:
  - .  # reload docs for any file changes
use_directory_urls: false